# Generated by Django 2.2.8 on 2020-01-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieee', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='image/default/no_image.png', upload_to='image'),
        ),
    ]
