# Generated by Django 2.2.8 on 2020-01-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieee', '0004_auto_20200106_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default/no_image.png', upload_to='image'),
        ),
    ]
