# Generated by Django 2.2.8 on 2020-03-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icon', verbose_name='アイコン'),
        ),
    ]
